export const mockData = {
    reading:{
        1: ["B"],
        2: ["G"],
        3: ["D"],
        4: ["H"],
        5: ["A"],
        6: ["I"],
        7: ["F"],
        8: ["E"],
        9: ["G"],
        10: ["H"],
        11: ["F"],
        12: ["D"],
        13: ["A"],
        14: ["E"],
        15: ["A"],
        16: ["H"],
        17: ["F"],
        18: ["B"],
        19: ["G"],
        20: ["B"],
        21: ["A"],
        22: ["C"],
        23: ["B"],
        24: ["A"],
        25: ["C"],
        26: ["A"],
    },
    grammar:{
        1: ["beginning"],
        2: ["broken","breaking"],
        3: ["unrealistic"],
        4: ["yourself"],
        5: ["necessarily"],
        6: ["motivation","motive"],
        7: ["expected"],
        8: ["realise","realize"],
        9: ["as","like"],
        10: ["than"],
        11: ["it"],
        12: ["only"],
        13: ["the","its"],
        14: ["of"],
        15: ["out"],
        16: ["in"],
        17: ["C"],
        18: ["A"],
        19: ["B"],
        20: ["D"],
        21: ["B"],
        22: ["A"],
        23: ["A"],
        24: ["B"],
        25: ["C"]
    },
    listening: {
        1: ["B"],
        2: ["B"],
        3: ["A"],
        4: ["C"],
        5: ["A"],
        6: ["B"],
        7: ["B"],
        8: ["A"],
        9: ["A"],
        10: ["A"],
        11: ["AB"],
        12: ["B"],
        13: ["B"],
        14: ["B"],
        15: ["animal shelter"],
        16: ["catches mice"],
        17: ["peoples keyboards"],
        18: ["city council","City Council"],
        19: ["allergy attack", "allergic attack"],
        20: ["big attraction"],
        21: ["local paper", "local newspaper"],
        22: ["mayor, city"],
    }
}